In [ ]:
'''
get data from 'https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/QI2T9A'
'''

In [1]:
import pandas as pd
from tqdm import tqdm

In [69]:
f = open("../dataverse_files/events.2014.20160121105408.tab", 'r')
output_dir = "../output/2014/"
# f = open("../dataverse_files/events.2018.20200427084805.tab", 'r')
# output_dir = "../output/2018/"
# f = open("../dataverse_files/events.2019.20200427085336.tab", 'r')
# output_dir = "../output/2019/"

In [70]:
data = f.read()
f.close()

In [71]:
data = data.split("\n")

In [72]:
data = [i.split("\t") for i in data]

In [73]:
for idx, i in enumerate(data):
    data[idx] = [j if j!= '' else None for j in i]

In [74]:
df = pd.DataFrame(data[1:-1])

In [75]:
df.columns = data[0]

In [76]:
df

,Event ID,Event Date,Source Name,Source Sectors,Source Country,Event Text,CAMEO Code,Intensity,Target Name,Target Sectors,Target Country,Story ID,Sentence Number,Publisher,City,District,Province,Country,Latitude,Longitude
0,20718170,2014-01-01,Police (Australia),"Police,Government",Australia,"Arrest, detain, or charge with legal action",173,-5,Men (Australia),"Social,General Population / Civilian / Social",Australia,32493690,2,Daily Telegraph,Surfers Paradise,Gold Coast,State of Queensland,Australia,-28.0027,153.43
1,20718171,2014-01-01,Police (Australia),"Police,Government",Australia,"Arrest, detain, or charge with legal action",173,-5,Children (Australia),"Social,General Population / Civilian / Social",Australia,32493693,1,Daily Telegraph,Maroubra,Randwick,State of New South Wales,Australia,-33.95,151.233
2,20718172,2014-01-01,Government Official (Democratic Republic of Co...,Government,Democratic Republic of Congo,Make statement,010,0,Attacker (Democratic Republic of Congo),"Criminals / Gangs,Dissident",Democratic Republic of Congo,32495112,3,The Australian,Kinshasa,None,Kinshasa City,Democratic Republic of Congo,-4.32142,15.3081
3,20718174,2014-01-01,Military (South Sudan),"Military,Government",South Sudan,Use conventional military force,190,-10,Armed Rebel (South Sudan),"Rebel,Dissident",South Sudan,32495113,1,The Australian,Juba,None,Central Equatoria State,South Sudan,4.85165,31.5825
4,20718173,2014-01-01,Armed Rebel (South Sudan),"Rebel,Dissident",South Sudan,Use unconventional violence,180,-9,Military (South Sudan),"Military,Government",South Sudan,32495113,1,The Australian,Juba,None,Central Equatoria State,South Sudan,4.85165,31.5825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879388,22329420,2014-12-31,Ministry (Jordan),Government,Jordan,Consult,040,1,Head of Government (Jordan),"Executive,Government,Executive Office",Jordan,37459368,2,Ad Dustour,Amman,None,Muhafazat `Amman,Jordan,31.9552,35.945
879389,22329425,2014-12-31,Egypt,None,Egypt,Host a visit,043,2.8,Somalia,None,Somalia,37459377,1,Al Shabiba,Cairo,None,Muhafazat al Qahirah,Egypt,30.0626,31.2497
879390,22329424,2014-12-31,Abdel Fattah Al-Sisi,"Elite,International Religious,Executive Office...",Egypt,Consult,040,1,Head of Government (Somalia),"Executive,Executive Office,Government",Somalia,37459377,1,Al Shabiba,Cairo,None,Muhafazat al Qahirah,Egypt,30.0626,31.2497
879391,22329423,2014-12-31,Somalia,None,Somalia,Make a visit,042,1.9,Egypt,None,Egypt,37459377,1,Al Shabiba,Cairo,None,Muhafazat al Qahirah,Egypt,30.0626,31.2497
879392,22329422,2014-12-31,Head of Government (Somalia),"Executive,Executive Office,Government",Somalia,Consult,040,1,Abdel Fattah Al-Sisi,"Elite,International Religious,Executive Office...",Egypt,37459377,1,Al Shabiba,Cairo,None,Muhafazat al Qahirah,Egypt,30.0626,31.2497

In [77]:
len(df) - df['District'].isna().sum()

134758

In [78]:
df["District"].drop_duplicates()

0                          Gold Coast
1                            Randwick
2                                None
9                          Leichhardt
49                      Upper Bavaria
                     ...
878083                 Rapides Parish
878614              Ogba/Egbema/Ndoni
878675                     Wald Rabi'
878972                          Bajil
879016    Rabah Local Government Area
Name: District, Length: 3709, dtype: object

In [79]:
df["Story ID"].drop_duplicates()

0         32493690
1         32493693
2         32495112
3         32495113
7         32495121
            ...
879382    37459360
879383    37459363
879385    37459366
879387    37459368
879389    37459377
Name: Story ID, Length: 454746, dtype: object

In [80]:
df["Source Name"].drop_duplicates()

0                                        Police (Australia)
2         Government Official (Democratic Republic of Co...
3                                    Military (South Sudan)
4                                 Armed Rebel (South Sudan)
6                                 Rebel Group (South Sudan)
                                ...
878675        Combatant (Al Qaeda in the Arabian Peninsula)
878712                                Attacker (Cape Verde)
878957                               Media Personnel (Cuba)
879001                               Martin Belaunde Lossio
879198                                      Actor (Tunisia)
Name: Source Name, Length: 25676, dtype: object

In [81]:
df["Event Text"].drop_duplicates() ## 260 kinds of event ( predicate )

0               Arrest, detain, or charge with legal action
2                                            Make statement
3                           Use conventional military force
4                               Use unconventional violence
7                   fight with small arms and light weapons
                                ...
700096                  Reject request for humanitarian aid
721210              Ease restrictions on political freedoms
724987                          Demand economic cooperation
830924                 Engage in violent protest for rights
875575    Threaten to impose state of emergency or marti...
Name: Event Text, Length: 260, dtype: object

In [82]:
df["CAMEO Code"].drop_duplicates() ## 260 kinds of event ( predicate )

0          173
2          010
3          190
4          180
7          193
          ...
700096    1223
721210    0811
724987    1011
830924    1453
875575    1324
Name: CAMEO Code, Length: 260, dtype: object

In [83]:
df["Intensity"] = df["Intensity"].apply(float)

In [84]:
min(df["Intensity"])

-10.0

In [85]:
max(df["Intensity"])

10.0

In [86]:
df.isna().sum()

Event ID                0
Event Date              0
Source Name             0
Source Sectors     172917
Source Country      38383
Event Text              0
CAMEO Code              0
Intensity               0
Target Name             0
Target Sectors     255739
Target Country      54094
Story ID                0
Sentence Number         0
Publisher               0
City               241373
District           744635
Province           156458
Country               329
Latitude              329
Longitude             329
dtype: int64

In [87]:
df = df.replace('', None)

In [88]:
len(set(list(df["Target Name"].drop_duplicates()) + list(df["Source Name"].drop_duplicates())))

30638

In [89]:
pd.DataFrame( df.iloc[0,:]).to_dict()

{0: {'Event ID': '20718170',
  'Event Date': '2014-01-01',
  'Source Name': 'Police (Australia)',
  'Source Sectors': 'Police,Government',
  'Source Country': 'Australia',
  'Event Text': 'Arrest, detain, or charge with legal action',
  'CAMEO Code': '173',
  'Intensity': -5.0,
  'Target Name': 'Men (Australia)',
  'Target Sectors': 'Social,General Population / Civilian / Social',
  'Target Country': 'Australia',
  'Story ID': '32493690',
  'Sentence Number': '2',
  'Publisher': 'Daily Telegraph',
  'City': 'Surfers Paradise',
  'District': 'Gold Coast',
  'Province': 'State of Queensland',
  'Country': 'Australia',
  'Latitude': '-28.0027',
  'Longitude': '153.43'}}

In [90]:
filtered_df = df[["Source Name", "Event Text", "Target Name", "Event Date", "Intensity", "Publisher", "Country", "City", "Province", "Longitude", "Latitude"]]

In [91]:
filtered_df

,Source Name,Event Text,Target Name,Event Date,Intensity,Publisher,Country,City,Province,Longitude,Latitude
0,Police (Australia),"Arrest, detain, or charge with legal action",Men (Australia),2014-01-01,-5.0,Daily Telegraph,Australia,Surfers Paradise,State of Queensland,153.43,-28.0027
1,Police (Australia),"Arrest, detain, or charge with legal action",Children (Australia),2014-01-01,-5.0,Daily Telegraph,Australia,Maroubra,State of New South Wales,151.233,-33.95
2,Government Official (Democratic Republic of Co...,Make statement,Attacker (Democratic Republic of Congo),2014-01-01,0.0,The Australian,Democratic Republic of Congo,Kinshasa,Kinshasa City,15.3081,-4.32142
3,Military (South Sudan),Use conventional military force,Armed Rebel (South Sudan),2014-01-01,-10.0,The Australian,South Sudan,Juba,Central Equatoria State,31.5825,4.85165
4,Armed Rebel (South Sudan),Use unconventional violence,Military (South Sudan),2014-01-01,-9.0,The Australian,South Sudan,Juba,Central Equatoria State,31.5825,4.85165
...,...,...,...,...,...,...,...,...,...,...,...
879388,Ministry (Jordan),Consult,Head of Government (Jordan),2014-12-31,1.0,Ad Dustour,Jordan,Amman,Muhafazat `Amman,35.945,31.9552
879389,Egypt,Host a visit,Somalia,2014-12-31,2.8,Al Shabiba,Egypt,Cairo,Muhafazat al Qahirah,31.2497,30.0626
879390,Abdel Fattah Al-Sisi,Consult,Head of Government (Somalia),2014-12-31,1.0,Al Shabiba,Egypt,Cairo,Muhafazat al Qahirah,31.2497,30.0626
879391,Somalia,Make a visit,Egypt,2014-12-31,1.9,Al Shabiba,Egypt,Cairo,Muhafazat al Qahirah,31.2497,30.0626
879392,Head of Government (Somalia),Consult,Abdel Fattah Al-Sisi,2014-12-31,1.0,Al Shabiba,Egypt,Cairo,Muhafazat al Qahirah,31.2497,30.0626

In [92]:
filtered_df.columns

Index(['Source Name', 'Event Text', 'Target Name', 'Event Date', 'Intensity',
       'Publisher', 'Country', 'City', 'Province', 'Longitude', 'Latitude'],
      dtype='object')

In [93]:
all_entity= set(\
list(filtered_df['Source Name']) +\
list(filtered_df['Target Name']) + \
list(filtered_df['Publisher']) + \
list(filtered_df['Publisher']) +\
list(filtered_df['Country']) +\
list(filtered_df['City']) +\
list(filtered_df['Province']))

In [94]:
all_relation = list(set(list(filtered_df['Event Text']) + ["Intensity", 'Publisher','Country', 'City', 'Province', 'Longitude', 'Latitude']))

In [95]:
entity2id = dict()
id2entity = dict()
for idx, entity in enumerate(all_entity):
    entity2id[entity] = idx
    id2entity[idx] = entity

In [96]:
relation2id = dict()
id2relation = dict()
for idx, relation in enumerate(all_relation):
    relation2id[relation] = idx
    id2relation[idx] = relation

In [97]:
dates = list(filtered_df["Event Date"].drop_duplicates())

In [98]:
timestamp2idx = dict()
for idx, t in enumerate(dates):
    timestamp2idx[t] = idx

In [99]:
train_idx = int(len(filtered_df) * 0.8)
valid_idx = int(len(filtered_df) * 0.9)
flag = 0
train = open(output_dir + "train.txt" , 'w')
valid = open(output_dir + "valid.txt" , 'w')
test = open(output_dir + "test.txt" , 'w')
with open(output_dir + "data.txt" , 'w') as f:
    for idx, row in tqdm(filtered_df.iterrows()):
        outrow = ""
        outrow += str(entity2id[row["Source Name"]])
        outrow += "\t"
        outrow += str(relation2id[row["Event Text"]])
        outrow += "\t"
        outrow += str(entity2id[row["Target Name"]])
        outrow += "\t"
        
        outrow += str(timestamp2idx[row["Event Date"]])
        outrow += "\t"        
        
        outrow += str(row["Event Date"])
        outrow += "\t"
        
        if row["Event Date"].split("-")[-2] == '11':
            flag = 1 
        elif row["Event Date"].split("-")[-2] == '12':
            flag = 2
        outrow += str(relation2id["Intensity"])
        outrow += "\t"
        outrow += str(row["Intensity"])
        outrow += "\t"
        
        if row["Publisher"] != None:
            outrow += str(relation2id["Publisher"])
            outrow += "\t"
            outrow += str(entity2id[row["Publisher"]])
            outrow += "\t"
            
        if row["Country"] != None:    
            outrow += str(relation2id["Country"])
            outrow += "\t"
            outrow += str(entity2id[row["Country"]])
            outrow += "\t"
            
        if row["City"] != None:
            outrow += str(relation2id["City"])
            outrow += "\t"
            outrow += str(entity2id[row["City"]])
            outrow += "\t"
        
        if row["Province"] != None:
            outrow += str(relation2id["Province"])
            outrow += "\t"
            outrow += str(entity2id[row["Province"]])
            outrow += "\t"
        if row["Longitude"] != None:
            outrow += str(relation2id["Longitude"])
            outrow += "\t"
            outrow += str(row["Longitude"])
            outrow += "\t"   
        if row["Latitude"] != None:
            outrow += str(relation2id["Latitude"])
            outrow += "\t"
            outrow += str(row["Latitude"]) 
            outrow += "\t"
        outrow = outrow[:-1]
        outrow += "\n"
            
#         if idx == train_idx:
#             flag = 1
#         elif idx == valid_idx:
#             flag = 2
            
        if flag == 0 :
            train.write(outrow)
        elif flag == 1:
            valid.write(outrow)
        elif flag == 2:
            test.write(outrow)
        f.write(outrow)
train.close()
valid.close()
test.close()

879393it [03:09, 4641.56it/s]

In [100]:
with open(output_dir + "entity2id.txt" , 'w') as f:
    for entity, idx in entity2id.items():
        f.write(str(entity) + "\t" + str(idx) + "\n")

In [101]:
with open(output_dir + "relation2id.txt" , 'w') as f:
    for relation, idx in relation2id.items():
        f.write(str(relation) + "\t" + str(idx) + "\n")

In [102]:
# filtered_df[filtered_df["Event Date"] == '2018-11-01'][:50]